### ISSUE TITLE
Fails with 'Error: connect ECONNREFUSED 198.54.117.197:443'

### ISSUE THREAD

**Issue by axelf4** [leafo/gh-actions-luarocks#1]
Hi! I am trying to setup continuous integration using this action for [this repository](https://github.com/axelf4/llr-test) but keep hitting this error:

```
2020-04-12T16:31:25.2203664Z ##[group]Run leafo/gh-actions-luarocks@v2
2020-04-12T16:31:25.2203781Z with:
2020-04-12T16:31:25.2203869Z   luaRocksVersion: 3.3.1
2020-04-12T16:31:25.2203954Z ##[endgroup]
2020-04-12T16:31:25.4235022Z ##[error]Failed to install LuaRocks: Error: connect ECONNREFUSED 198.54.117.197:443
```

This happens consistently and also  with `luaRocksVersion == 3.2.0`. Am I doing something wrong or is this just the LuaRocks servers being down, or something that could be fixed?

<details>
<summary>GitHub actions workflow</summary>
<pre><code>
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        luaVersion: ["5.3", "luajit"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v5
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v2
        with:
          luaRocksVersion: "3.3.1"
      - name: Run tests
        run: luarocks test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
      - name: Run Luacheck
        run: luacheck .
</code></pre>
</details>

**Comment by leafo** [comment]
The issues is because luarocks.org is down. I'm trying to get that resolved.

Potential solution could configuring a mirror to sit above the default sever. I thought the luarocks tool would be able to fall back to a default mirror but maybe there's a bug preventing that.

**Comment by leafo** [comment]
The official IP of the server is currently 45.33.61.132, so you can also try inserted a hosts record manually.

**Comment by axelf4** [comment]
Ah ok, thanks. Got confused because meanwhile the URL was working in my browser. Seems to be working now though, so feel free to close.

**Comment by leafo** [comment]
The luarocks website is back now. Although we did spot a bug with the tool for the backup manifest, this action pulls directly from the luarocks domain. Maybe a future update could be to pull from a backup server if the primary one is down.
