### ISSUE TITLE
Default LuaRocks version is still 3.5.0

### ISSUE THREAD

**Issue by vadi2** [leafo/gh-actions-luarocks#11]
Has https://github.com/leafo/gh-actions-luarocks/commit/342b89dd0b6bdad10656ba0b11dd83c4872ae63b been published to the marketplace? The default still seems to be `3.5.0`:

![image](https://user-images.githubusercontent.com/110988/158531024-249b5ff3-63a2-43a1-96fa-a3a32e8bdaaa.png)

See https://github.com/Mudlet/Mudlet/runs/5565729809?check_suite_focus=true

**Comment by zaunist** [comment]
Because it is not release newer version...

**Comment by leafo** [comment]
Sorry about that, v4 has been updated. If you ever get stuck you can use @master or @hash to access a specific ref that may not have been published as a version yet.

**Comment by zaunist** [comment]
> Sorry about that, v4 has been updated. If you ever get stuck you can use @master or @hash to access a specific ref that may not have been published as a version yet.

Thanks a lot.
