### ISSUE TITLE
Doesn't run on macOS

### ISSUE THREAD

**Issue by vadi2** [leafo/gh-actions-luarocks#3]
I need to use this action to install rocks on Ubuntu, macOS, and Windows - and it seems only Ubuntu is supported:

> sudo: apt-get: command not found

**Comment by alerque** [comment]
This action doesn't use apt-get at all any more. I believe this issue is obsolete. That doesn't mean it works on macOS, just that somebody needs to retest this because this error is only relevant to a completely deprecated version of the Action.

**Comment by leafo** [comment]
Confirmed macos already works: https://github.com/leafo/gh-actions-luarocks/runs/5697000481
