### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by alerque** [leafo/gh-actions-luarocks#5]
Please consider using semver for future releases for this (and gh-actions-lua). GitHub Actions has a crazy system where they encourage semver + "major version" tags that are sliding (and updated with each semver tag), so people can use the major version tags to stay updated while not moving past non-breaking updates (like the latest releases of these two actions).

It's kind of a pain to update a whole bunch of projects for a non-breaking Action update. I don't love the retagging method either but at this point there is strong precedent for it's use with Actions and I don't know of a better solution.

**Comment by leafo** [comment]
luarocks action is now version 4.0.0 and lua action is now 8.0.0!

**Comment by alerque** [comment]
Thanks, that covers the semver part. One part left to go: for the GHA sliding major version tags, the latest `vX.Y.Z` tag should *additionally* be tagged as `vX` (a tag that will get moved to point to a different commit for each semver release).

**Comment by leafo** [comment]
I see, this isn't a feature of github actions, this is just me rewriting the version X tag on every update

**Comment by alerque** [comment]
True. Or use [a workflow like this one](https://github.com/theleagueof/fontship/blob/master/.github/workflows/versioning.yml).

(And thanks!)
